//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_63134144.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public string Id_job { get; set; }
        public string Id_hr { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Tstart { get; set; }
        public Nullable<System.TimeSpan> Tend { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Support { get; set; }
        public string Sta { get; set; }
        public string Pay { get; set; }
        public string Id_user { get; set; }
        public string Note { get; set; }
        public string Id_change { get; set; }
        public string Status_change { get; set; }
        public string Location { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual HR HR { get; set; }
    }
}
