//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_63134144.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.JOBS = new HashSet<JOB>();
        }
    
        public string Id_user { get; set; }
        public string Ho { get; set; }
        public string Ten_lot { get; set; }
        public string Ten { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string Dia_chi { get; set; }
        public Nullable<System.DateTime> Ngsinh { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<int> Kind { get; set; }
        public string Gtinh { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<short> Bad { get; set; }
        public byte[] PasswordHash { get; set; }
        public string Stk { get; set; }
        public string Bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBS { get; set; }
    }
}
